POST http://localhost:5000/bids/place-bid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3ZmE3N2VmLWI4ZjEtNDBjMS05ZjAwLTJhNTRkNzlhZTJlMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbGlpbXJhbjA0MDVAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWxpaW1yYW4wNDA1QGdtYWlsLmNvbSIsIkZpcnN0TmFtZSI6IkFsaSIsIkxhc3ROYW1lIjoiSW1yYW4iLCJDdXN0b21Vc2VybmFtZSI6ImFsaWltcmFuMjAwMiIsImV4cCI6MTc1NDcwMDk1NywiaXNzIjoiUXVpY2tTZWxsQVBJIiwiYXVkIjoiUXVpY2tTZWxsIn0.KqDvws5q-ljusRKAtHWWnhDbmLKOMS5vYliuZ4DrIkE

{
   "itemId": 19,
   "bidAmount": 500
}