GET http://localhost:5000/general-items

###
GET http://localhost:5000/general-items?category=Electronics

###
GET http://localhost:5000/general-items/2016

###
POST http://localhost:5000/general-items
Content-Type: application/json

{
    "Name": "Samsung Remote Controller",
    "ListedPrice": 99,
    "Category": "Electronics",
    "Thumbnail": "/assets/name_of_new_image.jpeg",
    "Description": "Some new description",
    "UsedStatus": "New"
}

###
PUT http://localhost:5000/general-items/4202
Content-Type: multipart/form-data

{
    "Name": "Kul Skjorte",
    "ListedPrice": 200,
    "Category": "others",
    "Thumbnail": "/assets/headphone_test_img.jpeg",
    "MainImages": [
        "/assets/headphones_main_1.webp",
        "/assets/headphones_main_2.jpeg"
    ],
    "Description": "This is a PUT request",
    "UsedStatus": "Used - Visibly Used",
    "PostCode": "0645",
    "Area": "Oslo"
}